from __future__ import annotations

"""Research-only margin-informed challenger.

F-MI-01 predicts home scoring margin with a fixed ridge model and maps *out-of-sample*
margin predictions to win probability. Every target-season prediction is generated by a
model fit only on earlier seasons. The probability mapper itself is trained only on margin
predictions that were already out of sample in still-earlier seasons.

Production forecasting does not import this module.
"""

from dataclasses import dataclass

import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

MARGIN_ALPHA = 20.0
PROBABILITY_C = 1000.0
OOF_START_SEASON = 2018
TARGET_SEASONS = (2022, 2023, 2024, 2025)


@dataclass(frozen=True)
class MarginInformedResult:
    predictions: pd.DataFrame
    calibration_rows: pd.DataFrame


def _feature_pipeline() -> Pipeline:
    return Pipeline(
        [
            ("imputer", SimpleImputer(strategy="median")),
            ("scale", StandardScaler()),
            ("ridge", Ridge(alpha=MARGIN_ALPHA)),
        ]
    )


def build_margin_oof(
    frame: pd.DataFrame,
    feature_columns: list[str],
    *,
    start_season: int = OOF_START_SEASON,
    end_season: int = max(TARGET_SEASONS),
) -> pd.DataFrame:
    """Generate expanding-window expected-margin predictions.

    Final margin is used only as the training target for seasons strictly before the
    season being scored. Rows without a known final margin are excluded.
    """
    required = {"season", "margin", "home_win"} | set(feature_columns)
    missing = required - set(frame.columns)
    if missing:
        raise ValueError(f"Margin research frame missing columns: {sorted(missing)}")
    if not feature_columns:
        raise ValueError("Margin research requires at least one football feature")

    work = frame.copy()
    work["season_num"] = pd.to_numeric(work["season"], errors="coerce")
    work["margin_num"] = pd.to_numeric(work["margin"], errors="coerce")
    work = work[work["margin_num"].notna() & work["home_win"].notna()].copy()
    if work.empty:
        raise ValueError("No completed historical games available for margin research")
    if int(work["season_num"].max()) > 2025:
        raise ValueError("F-MI-01 may not use outcomes after 2025")

    parts: list[pd.DataFrame] = []
    for season in range(int(start_season), int(end_season) + 1):
        train = work[work["season_num"] < season]
        test = work[work["season_num"] == season]
        if test.empty:
            continue
        if train.empty or train["margin_num"].notna().sum() < 300:
            continue
        model = _feature_pipeline()
        model.fit(train[feature_columns], train["margin_num"])
        part = test[["season", "home_win", "margin"]].copy()
        part["expected_margin"] = model.predict(test[feature_columns])
        parts.append(part)

    if not parts:
        raise RuntimeError("Margin research produced no out-of-sample predictions")
    return pd.concat(parts).sort_index()


def map_oof_margin_to_win_probability(
    margin_oof: pd.DataFrame,
    *,
    target_seasons: tuple[int, ...] = TARGET_SEASONS,
) -> MarginInformedResult:
    """Nested calibration from OOF expected margin to win probability.

    For target season S, the logistic mapper fits only OOF margin predictions from
    seasons < S. Therefore neither the margin model nor its probability calibration sees
    any outcome from the season being scored.
    """
    required = {"season", "home_win", "expected_margin", "margin"}
    missing = required - set(margin_oof.columns)
    if missing:
        raise ValueError(f"Margin OOF missing columns: {sorted(missing)}")

    work = margin_oof.copy()
    work["season_num"] = pd.to_numeric(work["season"], errors="coerce")
    outputs: list[pd.DataFrame] = []
    calibration_meta: list[dict] = []
    for season in target_seasons:
        calibration = work[work["season_num"] < season]
        test = work[work["season_num"] == season]
        if test.empty:
            continue
        if calibration.empty or calibration["home_win"].nunique() < 2:
            raise RuntimeError(f"Insufficient nested calibration history for {season}")
        mapper = LogisticRegression(C=PROBABILITY_C, max_iter=3000, solver="lbfgs")
        mapper.fit(calibration[["expected_margin"]], calibration["home_win"].astype(int))
        probability = mapper.predict_proba(test[["expected_margin"]])[:, 1]
        part = test[["season", "home_win", "margin", "expected_margin"]].copy()
        part["probability"] = np.clip(probability, 1e-6, 1.0 - 1e-6)
        outputs.append(part)
        calibration_meta.append(
            {
                "season": int(season),
                "calibration_games": int(len(calibration)),
                "calibration_first_season": int(calibration["season_num"].min()),
                "calibration_last_season": int(calibration["season_num"].max()),
                "intercept": float(mapper.intercept_[0]),
                "margin_coefficient": float(mapper.coef_[0, 0]),
            }
        )

    if not outputs:
        raise RuntimeError("Margin-informed probability mapping produced no target predictions")
    predictions = pd.concat(outputs).sort_index()
    missing_targets = set(target_seasons) - set(predictions["season"].astype(int).unique())
    if missing_targets:
        raise RuntimeError(f"Missing margin-informed target seasons: {sorted(missing_targets)}")
    return MarginInformedResult(predictions, pd.DataFrame(calibration_meta))


def run_margin_informed(
    frame: pd.DataFrame,
    feature_columns: list[str],
    *,
    target_seasons: tuple[int, ...] = TARGET_SEASONS,
) -> MarginInformedResult:
    oof = build_margin_oof(
        frame,
        feature_columns,
        start_season=OOF_START_SEASON,
        end_season=max(target_seasons),
    )
    return map_oof_margin_to_win_probability(oof, target_seasons=target_seasons)
