from pathlib import Path

# 1) Make QB/recent-series public rendering structured and subject-specific.
path = Path('src/nfl_forecast/editorial_voice.py')
text = path.read_text()
needle = '''        if fam == "qb_opponent_history":\n            match = re.search(\n                r"^In the nflverse play-by-play sample since 2021, (.+?) has ([0-9]+) meaningful games against ([A-Z]{2,4}); the most recent was (.+?)\\. Over ([0-9]+) charted dropbacks in those games, (?:he|she|they) averaged ([+\\-][0-9.]+) EPA/dropback with a ([0-9.]+)% positive-EPA rate",\n                summary,\n            )\n            if match:\n                quarterback, games, opponent, latest, dropbacks, epa, positive = match.groups()\n                return f"{quarterback}–{opponent} recent sample: {games} meaningful games, {dropbacks} dropbacks, {epa} EPA/dropback, {positive}% positive-EPA; latest: {latest}."\n        if fam == "rivalry":\n'''
replacement = '''        if fam == "qb_opponent_history":\n            meta = item.get("metadata") or {}\n            title = str(item.get("title") or "").strip()\n            quarterback = title.split(" vs ", 1)[0].strip() if " vs " in title else "Quarterback"\n            opponent = title.split(" vs ", 1)[1].split(":", 1)[0].strip() if " vs " in title else "opponent"\n            meetings = list(meta.get("meetings") or [])\n            meaningful = [row for row in meetings if float(row.get("dropbacks") or 0) >= 10]\n            games = int(meta.get("recent_sample_games") or meta.get("games") or len(meaningful) or 0)\n            dropbacks = int(item.get("sample_size") or sum(int(row.get("dropbacks") or 0) for row in meaningful) or 0)\n            epa = meta.get("epa_per_dropback")\n            success = meta.get("success_rate")\n            latest = meta.get("latest_meeting") or (sorted(meaningful, key=lambda row: (row.get("season") or 0, row.get("week") or 0), reverse=True)[0] if meaningful else {})\n            latest_label = str(latest.get("human_label") or latest.get("label") or "").strip() if isinstance(latest, dict) else ""\n            if games:\n                parts = [f"{quarterback}–{opponent} recent file: {games} meaningful meetings"]\n                if dropbacks:\n                    parts.append(f"{quarterback} logged {dropbacks} charted dropbacks")\n                if epa is not None and success is not None:\n                    parts.append(f"{quarterback} produced {float(epa):+.2f} EPA/dropback with {float(success):.0%} positive-EPA")\n                if latest_label:\n                    parts.append(f"latest {quarterback}–{opponent} entry: {latest_label}")\n                return "; ".join(parts) + "."\n            return f"{quarterback}–{opponent} recent history is too sparse for a stable {quarterback} aggregate."\n        if fam in {"rivalry", "recent_series"}:\n'''
if needle not in text:
    raise SystemExit('QB/rivalry renderer insertion point missing')
text = text.replace(needle, replacement)

old = '''            match = re.search(\n                r"^Since 2021, ([A-Za-z0-9]+) and ([A-Za-z0-9]+) have played ([0-9]+) completed games in the nflverse schedule sample: ([A-Za-z0-9]+) is ([0-9]+-[0-9]+)\\. The most recent finished (.+?)\\.$",\n                summary,\n            )\n            if match:\n                team_a, team_b, games, leader, record, latest = match.groups()\n                return f"{team_a}-{team_b} since 2021: {games} meetings, {leader} {record}; latest: {latest}."\n'''
new = '''            match = re.search(\n                r"^Since 2021, ([A-Za-z0-9]+) and ([A-Za-z0-9]+) have played ([0-9]+) completed games in the nflverse schedule sample: ([A-Za-z0-9]+) is ([0-9]+-[0-9]+)(?: with ([0-9]+) ties?)?\\. The most recent finished (.+?)\\.$",\n                summary,\n            )\n            if match:\n                team_a, team_b, games, leader, record, ties, latest = match.groups()\n                tie_note = f", {ties} ties" if ties else ""\n                return f"{team_a}-{team_b} recent series: {games} meetings; {leader} {record}{tie_note}; latest {team_a}-{team_b} result: {latest}."\n'''
if old not in text:
    raise SystemExit('recent-series regex block missing')
text = text.replace(old, new)

# Stop numeric captures from swallowing terminal punctuation (e.g. +0.01..).
text = text.replace('([+\\-][0-9.]+) EPA per early-down pass\\. ([A-Z]{2,4}) allowed ([+\\-][0-9.]+)', '([+\\-][0-9]+(?:\\.[0-9]+)?) EPA per early-down pass\\. ([A-Z]{2,4}) allowed ([+\\-][0-9]+(?:\\.[0-9]+)?)')
text = text.replace('([+\\-][0-9.]+) EPA/play from shotgun; ([A-Z]{2,4}) allowed ([+\\-][0-9.]+)', '([+\\-][0-9]+(?:\\.[0-9]+)?) EPA/play from shotgun; ([A-Z]{2,4}) allowed ([+\\-][0-9]+(?:\\.[0-9]+)?)')
text = text.replace('([+\\-][0-9.]+) EPA/play; \\1 allowed ([+\\-][0-9.]+)', '([+\\-][0-9]+(?:\\.[0-9]+)?) EPA/play; \\1 allowed ([+\\-][0-9]+(?:\\.[0-9]+)?)')
path.write_text(text)

# 2) Ordinary recent divisional series belongs in notebook; it must not replace
# an already slate-aware Read. Only the genuinely one-off Melbourne event may.
path = Path('scripts/polish_publication.py')
text = path.read_text()
old = '''            elif rivalry:\n                preview["headline"] = _expand(rivalry.get("title") or preview.get("headline") or f"{away}-{home}")\n                special_first = _expand(rivalry.get("summary") or "")\n\n            if special_first:\n'''
if old not in text:
    raise SystemExit('ordinary rivalry promotion block missing')
text = text.replace(old, '''            if special_first:\n''')
path.write_text(text)

# 3) Regression tests.
path = Path('tests/test_editorial_evidence_compositor.py')
text = path.read_text()
addition = r'''\n\ndef test_qb_history_public_copy_uses_structured_subject_specific_facts():\n    predictions = pd.DataFrame([{"game_id":"g","away_team":"NYG","home_team":"DAL","pick":"DAL"}])\n    title = "Dak Prescott vs NYG: player history"\n    previews = {"g": {"headline":"old","paragraphs":["old"],"story_spine":{"primary_title":title},"key_factors":[{"title":title,"summary":"Dak Prescott has faced NYG 8 times; the most recent was last season, Week 18.","metadata":{"family":"qb_opponent_history"}}],"matchup_meter":[],"notebook":[]}}\n    evidence = {"g": [{"title":title,"summary":"Dak Prescott has faced NYG 8 times; the most recent was last season, Week 18.","sample_size":257,"metadata":{"family":"qb_opponent_history","games":8,"epa_per_dropback":0.24,"success_rate":0.55,"latest_meeting":{"human_label":"2025 Week 18"},"meetings":[{"season":2025,"week":18,"dropbacks":32,"human_label":"2025 Week 18"}]}}]}\n    out = polish_preview_slate(previews, predictions, evidence)["g"]\n    public = " ".join([out["paragraphs"][0], out["case_for_pick"], out["case_for_opponent"]])\n    assert "Dak Prescott–NYG recent file" in public\n    assert "Dak Prescott logged 257 charted dropbacks" in public\n    assert "has faced NYG 8 times; the most recent" not in public\n\n\ndef test_recent_series_public_copy_removes_source_method_scaffold():\n    predictions = pd.DataFrame([{"game_id":"g","away_team":"NYG","home_team":"DAL","pick":"DAL"}])\n    title = "NYG-DAL: division rivalry"\n    previews = {"g": {"headline":"old","paragraphs":["old"],"story_spine":{"primary_title":title},"key_factors":[{"title":title,"summary":"placeholder enough words for selection here today","metadata":{"family":"rivalry"}}],"matchup_meter":[],"notebook":[]}}\n    evidence = {"g": [{"title":title,"summary":"Since 2021, NYG and DAL have played 10 completed games in the nflverse schedule sample: NYG is 3-7. The most recent finished NYG 17, DAL 20.","metadata":{"family":"rivalry"}}]}\n    out = polish_preview_slate(previews, predictions, evidence)["g"]\n    public = " ".join([out["paragraphs"][0], out["case_for_pick"], out["case_for_opponent"]])\n    assert "NYG-DAL recent series: 10 meetings" in public\n    assert "completed games in the nflverse schedule sample" not in public\n'''
if 'test_qb_history_public_copy_uses_structured_subject_specific_facts' not in text:
    path.write_text(text + addition)

path = Path('tests/test_publication_polish.py')
text = path.read_text()
addition = r'''\n\ndef test_story_desk_keeps_ordinary_division_rivalry_in_notebook_not_read():\n    predictions = pd.DataFrame([{"game_id":"g","away_team":"NYG","home_team":"DAL","pick":"DAL","final_home_prob":.61,"pure_home_prob":.62,"market_home_prob":.58,"model_disagreement":.04}])\n    evidence = {"g": [{"category":"history","title":"NYG-DAL: division rivalry","summary":"Since 2021, NYG and DAL have played 10 completed games in the nflverse schedule sample: NYG is 3-7. The most recent finished NYG 17, DAL 20.","strength":"Strong","sample_size":10,"metadata":{"family":"rivalry"}}]}\n    previews = {"g": {"headline":"DAL protection vs NYG pass rush","paragraphs":["Keep this slate-aware Read.","Keep market paragraph."],"case_for_pick":"Keep DAL case.","case_for_opponent":"Keep NYG case.","what_could_make_us_wrong":"Keep failure mode.","editorial_voice":{"game_specific":True,"slate_aware":True},"notebook":[]}}\n    rewrite_previews(predictions, previews, evidence)\n    preview = previews["g"]\n    assert preview["paragraphs"][0] == "Keep this slate-aware Read."\n    assert preview["headline"] == "DAL protection vs NYG pass rush"\n    assert any("division rivalry" in item["title"] for item in preview["notebook"])\n'''
if 'test_story_desk_keeps_ordinary_division_rivalry_in_notebook_not_read' not in text:
    path.write_text(text + addition)
